services:
  fit-check-app:
    container_name: fit-check
    image: node:20
    working_dir: /app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "8081:8081" # Metro bundler
      - "19000:19000" # Expo dev tools
      - "19001:19001" # React Native dev
      - "19002:19002" # Expo web dev
    command: sh -c "npm install && npx expo start --tunnel"
    environment:
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - REACT_NATIVE_PACKAGER_HOSTNAME=localhost
    stdin_open: true
    tty: true
    restart: always